// Import the icon(s) you need
import {
  UserOutline,
  LaptopOutline,
  NotificationOutline,
  SettingOutline,
  PlusCircleOutline,
  ReloadOutline,
  PlusOutline,
  ArrowLeftOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  LayoutOutline,
  CarryOutOutline,
  BarChartOutline,
  BookOutline,
  DownloadOutline,
  UsergroupAddOutline,
  LoginOutline,
  LogoutOutline,
  LockOutline,
} from '@ant-design/icons-angular/icons';

export const iconsComponents = [
  UserOutline,
  LaptopOutline,
  NotificationOutline,
  SettingOutline,
  PlusCircleOutline,
  ReloadOutline,
  PlusOutline,
  ArrowLeftOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  BarChartOutline,
  BookOutline,
  LayoutOutline,
  CarryOutOutline,
  DownloadOutline,
  UsergroupAddOutline,
  LoginOutline,
  LogoutOutline,
  LockOutline,
];
